name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Publica ao fazer push na branch 'main'
      - release/*  # Também publica quando há uma tag de release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub using Token
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}  # Usando o token em vez da senha

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/automation-python-ticket-desk-manager:$GITHUB_SHA .
        docker tag ${{ secrets.DOCKER_USERNAME }}/automation-python-ticket-desk-manager:$GITHUB_SHA ${{ secrets.DOCKER_USERNAME }}/automation-python-ticket-desk-manager:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/automation-python-ticket-desk-manager:$GITHUB_SHA
        docker push ${{ secrets.DOCKER_USERNAME }}/automation-python-ticket-desk-manager:latest
